/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"

function Model(props) {
  const { nodes, materials } = useGLTF("/models/container.glb")
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Node2.geometry}
        material={materials.Container_Free}
      />
    </group>
  )
}

export default Model

useGLTF.preload("/models/container.glb")
